var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.findInternal=function(b,e,a){b instanceof String&&(b=String(b));for(var d=b.length,c=0;c<d;c++){var f=b[c];if(e.call(a,f,c,b))return{i:c,v:f}}return{i:-1,v:void 0}};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;$jscomp.ISOLATE_POLYFILLS=!1;$jscomp.FORCE_POLYFILL_PROMISE=!1;
$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(b,e,a){if(b==Array.prototype||b==Object.prototype)return b;b[e]=a.value;return b};$jscomp.getGlobal=function(b){b=["object"==typeof globalThis&&globalThis,b,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var e=0;e<b.length;++e){var a=b[e];if(a&&a.Math==Math)return a}throw Error("Cannot find global object");};$jscomp.global=$jscomp.getGlobal(this);
$jscomp.IS_SYMBOL_NATIVE="function"===typeof Symbol&&"symbol"===typeof Symbol("x");$jscomp.TRUST_ES6_POLYFILLS=!$jscomp.ISOLATE_POLYFILLS||$jscomp.IS_SYMBOL_NATIVE;$jscomp.polyfills={};$jscomp.propertyToPolyfillSymbol={};$jscomp.POLYFILL_PREFIX="$jscp$";var $jscomp$lookupPolyfilledValue=function(b,e){var a=$jscomp.propertyToPolyfillSymbol[e];if(null==a)return b[e];a=b[a];return void 0!==a?a:b[e]};
$jscomp.polyfill=function(b,e,a,d){e&&($jscomp.ISOLATE_POLYFILLS?$jscomp.polyfillIsolated(b,e,a,d):$jscomp.polyfillUnisolated(b,e,a,d))};$jscomp.polyfillUnisolated=function(b,e,a,d){a=$jscomp.global;b=b.split(".");for(d=0;d<b.length-1;d++){var c=b[d];if(!(c in a))return;a=a[c]}b=b[b.length-1];d=a[b];e=e(d);e!=d&&null!=e&&$jscomp.defineProperty(a,b,{configurable:!0,writable:!0,value:e})};
$jscomp.polyfillIsolated=function(b,e,a,d){var c=b.split(".");b=1===c.length;d=c[0];d=!b&&d in $jscomp.polyfills?$jscomp.polyfills:$jscomp.global;for(var f=0;f<c.length-1;f++){var h=c[f];if(!(h in d))return;d=d[h]}c=c[c.length-1];a=$jscomp.IS_SYMBOL_NATIVE&&"es6"===a?d[c]:null;e=e(a);null!=e&&(b?$jscomp.defineProperty($jscomp.polyfills,c,{configurable:!0,writable:!0,value:e}):e!==a&&($jscomp.propertyToPolyfillSymbol[c]=$jscomp.IS_SYMBOL_NATIVE?$jscomp.global.Symbol(c):$jscomp.POLYFILL_PREFIX+c,c=
$jscomp.propertyToPolyfillSymbol[c],$jscomp.defineProperty(d,c,{configurable:!0,writable:!0,value:e})))};$jscomp.polyfill("Array.prototype.find",function(b){return b?b:function(e,a){return $jscomp.findInternal(this,e,a).v}},"es6","es3");
define(["jquery","mage/template","jquery-ui-modules/widget"],function(b,e){b.widget("eloom.prdLstInfScroll",{options:{autoLoadMore:!0,link:{next:".pages-item-next a.next",prev:".pages-item-previous a.previous"},itemsWrap:".products.items.product-items",toolbar:".toolbar.toolbar-products",pager:".toolbar.toolbar-products .pages",loaderTmpl:"#cdz-lyn-loader"},_prepareAll:function(){this.$list=b(this.options.itemsWrap);this.$list.length?this._prepareHtml():this.interval&&clearInterval(this.interval)},
_create:function(){this._prepareAll();b("body").on("layeredNavLoaded",this._prepareAll.bind(this))},_getUrlParams:function(a){a=a.split("?");a=a[1]?a[1].split("&"):[];var d={},c,f=window.decodeURIComponent;for(c=0;c<a.length;c++){var h=a[c].split("=");d[f(h[0])]=void 0!==h[1]?f(h[1].replace(/\+/g,"%20")):""}return d},_getValueFromUrl:function(a,d,c){a=this._getUrlParams(a);return a[d]?(d=a[d].split("-"),d[c]?parseFloat(d[c]):parseFloat(d[0])):!1},_addParamsToUrl:function(a,d){var c=this._getUrlParams(a);
a=a.split("?")[0];var f=[];d=b.extend(c,d);b.each(d,function(h,g){f.push(h+"="+g)});return a+"?"+f.join("&")},_prepareHtml:function(){var a=this.options;this.$pool=b("#infscr-pool");if(!this.$pool.length){this.$pool=b('<div id="infscr-pool" class="infscr-pool">').insertAfter(this.$list).hide();this.processing=this.$loadPrev=this.$loadNext=this.$after=!1;a.autoLoadMore?this.$after=b('<div class="cdz-infscr-placeholder" role="infscr-after" style="height:1px">').insertAfter(this.$list):b(a.pager).last().find(a.link.next).length&&
(this.$loadNext=b(e("#cdz-lyn-view-next",{})).insertAfter(this.$list));this.loader={};this.pageItems=[];this.loader.next=b(e(a.loaderTmpl,{})).hide().insertAfter(this.$list);this.prePage=(this.prePage=parseInt(this._getValueFromUrl(document.URL,"p")))?this.prePage:1;this.pageUrl=document.URL;var d=this.$list.children();this.pageItems.push(d.first().attr("data-pageurl",this.pageUrl));this.pageItems.push(d.last().attr("data-pageurl",this.pageUrl));1<this.prePage&&(this.$loadPrev=b(e("#cdz-lyn-view-prev",
{})).insertBefore(this.$list),this.loader.prev=b(e(a.loaderTmpl,{})).hide().insertAfter(this.$loadPrev));this._bindEvents()}},_bindEvents:function(){var a=this;this.interval&&clearInterval(this.interval);this.interval=setInterval(function(){a.$after&&!a.processing&&a._checkVisible(a.$after)&&a._loadNext();b.each(a.pageItems,function(d,c){a._checkVisible(c)&&c.attr("data-pageUrl")!=a.pageUrl&&(a.pageUrl=c.attr("data-pageUrl"),window.history.replaceState({url:a.pageUrl},"",a.pageUrl))})},500);if(this.$loadNext)this.$loadNext.find("button").on("click",
a._loadNext.bind(this));if(this.$loadPrev)this.$loadPrev.find("button").on("click",a._loadPrev.bind(this))},_loadPrev:function(){if(1<this.prePage){var a=b(this.options.pager).last().find("a").first();a.length&&this._ajaxLoad("prev",this._addParamsToUrl(a.attr("href"),{p:this.prePage-1}))}},_loadNext:function(){this._ajaxLoad("next")},_ajaxLoad:function(a,d){this.processing=!0;var c=this,f=this.options;if(!d){var h=b(f.pager).last().find(f.link[a]);h.length&&(d=h.attr("href"))}d?(this.loader[a].show(),
b.ajax({url:d,data:{ajax_nav:1},type:"GET",cache:!0,success:function(g){if(g.category_products){var k=b(f.itemsWrap),m="next"==a?"appendTo":"prependTo",n=b(f.toolbar).last();c.$pool.html(g.category_products);var l=c.$pool.find(f.itemsWrap);l.length&&(k=l.children()[m](k),g=g.updated_url?g.updated_url:d,c.pageItems.push(k.first().attr("data-pageurl",g)),c.pageItems.push(k.last().attr("data-pageurl",g)));"prev"==a?(c.prePage--,1>=c.prePage&&c.$loadPrev.hide()):(g=c.$pool.find(f.toolbar).last(),g.length&&
n.replaceWith(g.removeAttr("data-mage-init")));c.$pool.empty();0==b(f.toolbar).last().find(f.link[a]).length&&c.$loadNext&&c.$loadNext.hide();setTimeout(function(){b("body").trigger("contentUpdated")},100)}}}).always(function(){setTimeout(function(){c.loader[a].hide();c.processing=!1},100)})):c.processing=!1},_checkVisible:function(a){var d=0<a.get(0).offsetWidth&&0<a.get(0).offsetHeight,c=a.is(":visible"),f=window.pageYOffset,h=f+window.innerHeight,g=a.offset().top;a=a.outerHeight(!0);a=g+a;return d&&
c&&(g<=f&&a>=f||g>=f&&g<=h||g>=f&&a<=h||g<=h&&a>=h)}});return b.eloom.prdLstInfScroll});
